/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_rafaelflores_31711187;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Faith
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cargarCategorias();
        this.cargarUsers();
        this.jdLogIn.setModal(true); 
        this.jdLogIn.pack();
        this.jdLogIn.setLocationRelativeTo(this);
        this.jdLogIn.setVisible(true);
        cargarChannels();
        cargarSuscripciones();
        cargarMisVideos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdLogIn = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnIngreso = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseñaR = new javax.swing.JTextField();
        txtUsuarioR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jdAgrVideo = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreVid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spnDuracion = new javax.swing.JSpinner();
        btnCrear = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtxASubtitulos = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAllChanels = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtSuscripciones = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSuscribirse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPlaylist = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstMisVideos = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblTituloVideo = new javax.swing.JLabel();
        btnLike = new javax.swing.JButton();
        btnDislike = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAComentarios = new javax.swing.JTextArea();
        lblSubtitulos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jdLogIn.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnIngreso.setText("Log In");
        btnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresoMouseClicked(evt);
            }
        });
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngreso)
                        .addGap(192, 192, 192))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnIngreso)
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("Log In", jPanel4);

        btnRegistro.setText("Registrarse");
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Edad");

        jLabel7.setText("Correo");

        jLabel8.setText("Contraseña");

        jLabel2.setText("Usuario");

        spnEdad.setModel(new javax.swing.SpinnerNumberModel(13, 13, 100, 1));

        jLabel14.setText("Categoria de Su Canal");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuarioR)
                    .addComponent(txtNombre)
                    .addComponent(txtCorreo)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRegistro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtContraseñaR)
                    .addComponent(spnEdad))
                .addGap(99, 99, 99))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseñaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Sign Up", jPanel5);

        javax.swing.GroupLayout jdLogInLayout = new javax.swing.GroupLayout(jdLogIn.getContentPane());
        jdLogIn.getContentPane().setLayout(jdLogInLayout);
        jdLogInLayout.setHorizontalGroup(
            jdLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jdLogInLayout.setVerticalGroup(
            jdLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jLabel15.setText("Crear Video");

        jLabel16.setText("Nombre");

        jLabel17.setText("Duracion");

        spnDuracion.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 5));

        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        txtxASubtitulos.setColumns(20);
        txtxASubtitulos.setRows(5);
        jScrollPane7.setViewportView(txtxASubtitulos);

        jLabel18.setText("Subtitulos");

        javax.swing.GroupLayout jdAgrVideoLayout = new javax.swing.GroupLayout(jdAgrVideo.getContentPane());
        jdAgrVideo.getContentPane().setLayout(jdAgrVideoLayout);
        jdAgrVideoLayout.setHorizontalGroup(
            jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAgrVideoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jdAgrVideoLayout.createSequentialGroup()
                        .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdAgrVideoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdAgrVideoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(70, 70, 70)))
                        .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jdAgrVideoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreVid)
                                    .addComponent(spnDuracion)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(jdAgrVideoLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdAgrVideoLayout.setVerticalGroup(
            jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAgrVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spnDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdAgrVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(jdAgrVideoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrear)
                .addGap(12, 12, 12))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstAllChanels.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(lstAllChanels);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("VideoJuegos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Musica");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cocina");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Otros");
        treeNode1.add(treeNode2);
        jtSuscripciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jtSuscripciones);

        jLabel10.setText("Todos los Canales");

        jLabel11.setText("Mis Suscripciones");

        btnSuscribirse.setText("Suscribirse");
        btnSuscribirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuscribirseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnSuscribirse)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnSuscribirse)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Historial", jPanel3);

        lstPlaylist.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(lstPlaylist);

        jLabel12.setText("Mi PlayList");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(507, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mi PlayList", jPanel2);

        lstMisVideos.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(lstMisVideos);

        jLabel13.setText("Mis Videos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(507, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mis Videos", jPanel6);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("YouLeo Tube");

        lblBienvenida.setText("Bienvenido:");

        lblTituloVideo.setText("jLabel3");

        btnLike.setText("Like");
        btnLike.setEnabled(false);

        btnDislike.setText("Dislike");
        btnDislike.setEnabled(false);

        txtAComentarios.setColumns(20);
        txtAComentarios.setRows(5);
        jScrollPane1.setViewportView(txtAComentarios);

        lblSubtitulos.setBackground(new java.awt.Color(0, 153, 153));
        lblSubtitulos.setText("Subtitulos");

        jButton1.setText("Nuevo Comentario");
        jButton1.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);

        btnFavoritos.setText("Agr. a Favoritos");
        btnFavoritos.setEnabled(false);

        jLabel9.setText("Comentarios");

        jMenu1.setText("Agregar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBienvenida)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTituloVideo)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(lblSubtitulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLike)
                                .addGap(7, 7, 7)
                                .addComponent(btnDislike)
                                .addGap(10, 10, 10)
                                .addComponent(btnFavoritos)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBienvenida))
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloVideo)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubtitulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLike)
                            .addComponent(btnDislike)
                            .addComponent(btnFavoritos)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSalvar)
                                .addComponent(btnCancelar)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseClicked
        if (this.txtUsuario.getText().equals("") || this.txtContraseña.getText().equals("")) {
            JOptionPane.showMessageDialog(this.jdLogIn, "Debe rellenar todos los campos!!!");
        }else{
            for (int i = 0; i < this.AllChanels.size(); i++) {
                if (AllChanels.get(i).getUsuario().equals(this.txtUsuario.getText()) && AllChanels.get(i).getContraseña().equals(this.txtContraseña.getText())) {
                    this.actual = AllChanels.get(i);
                    this.bienvenida();
                    this.jdLogIn.setVisible(false);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this.jdLogIn, "No coinciden el Email y la contraseña, Si no tiene cuenta Registrese");
        }
    }//GEN-LAST:event_btnIngresoMouseClicked

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        if (this.txtNombre.getText().equals("") || this.txtCorreo.getText().equals("")  || this.txtUsuarioR.getText().equals("") ||
            this.txtContraseñaR.getText().equals("")){
            JOptionPane.showMessageDialog(this.jdLogIn, "Debe rellenar todos los campos!!!");
        }else{
            String usr = this.txtUsuarioR.getText();
            for (int i = 0; i < AllChanels.size(); i++) {
                if (AllChanels.get(i).getUsuario().equals(usr)) {
                    JOptionPane.showMessageDialog(this.jdLogIn, "Debe seleccionar otro User");
                    return;
                }
            }
            Usuarios u = new Usuarios(this.txtNombre.getText(), this.txtCorreo.getText(), this.txtUsuarioR.getText(), this.txtContraseñaR.getText(),
            Integer.parseInt(this.spnEdad.getValue().toString()), new Canales(this.txtUsuarioR.getText(), this.cmbCategoria.getSelectedItem().toString()), new Playlist());
            this.AllChanels.add(u);
            //this.archivo =  new guardarUsuarios("./Users.raffles");
            this.archivo.setListaPersonas(AllChanels);
            this.archivo.EscribirBinario();
            this.actual = u;
            this.bienvenida();
            this.jdLogIn.setVisible(false);
        }
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        archivo.setListaPersonas(AllChanels);
        archivo.EscribirBinario();
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnSuscribirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuscribirseMouseClicked
        DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jtSuscripciones.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultListModel modeloLista = (DefaultListModel) this.lstAllChanels.getModel();
        boolean exist = false;
        int centinela = -1;
        
        Canales canalActual = ((Canales) modeloLista.get(this.lstAllChanels.getSelectedIndex()));
        
        switch (canalActual.getCategoria()) {
            case "VideoJuegos":
                ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(new DefaultMutableTreeNode(canalActual));
                if (canalActual.getVidPropios().size() != 0) {
                    for (int j = 0; j < canalActual.getVidPropios().size(); j++) {
                        ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(raiz.getChildAt(0).getChildCount()-1)).add(new DefaultMutableTreeNode(canalActual.getVidPropios().get(j)));
                    }
                }
                break;
            case "Musica":
                ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(new DefaultMutableTreeNode(canalActual));
                if (canalActual.getVidPropios().size() != 0) {
                    for (int j = 0; j < canalActual.getVidPropios().size(); j++) {
                        ((DefaultMutableTreeNode) raiz.getChildAt(1).getChildAt(raiz.getChildAt(1).getChildCount()-1)).add(new DefaultMutableTreeNode(canalActual.getVidPropios().get(j)));
                    }
                }
                break;
            case "Cocina":
                ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(new DefaultMutableTreeNode(canalActual));
                if (canalActual.getVidPropios().size() != 0) {
                    for (int j = 0; j < canalActual.getVidPropios().size(); j++) {
                        ((DefaultMutableTreeNode) raiz.getChildAt(2).getChildAt(raiz.getChildAt(2).getChildCount()-1)).add(new DefaultMutableTreeNode(canalActual.getVidPropios().get(j)));
                    }
                }
                break;
            case "Otros":
                ((DefaultMutableTreeNode) raiz.getChildAt(3)).add(new DefaultMutableTreeNode(canalActual));
                if (canalActual.getVidPropios().size() != 0) {
                    for (int j = 0; j < canalActual.getVidPropios().size(); j++) {
                        ((DefaultMutableTreeNode) raiz.getChildAt(3).getChildAt(raiz.getChildAt(3).getChildCount()-1)).add(new DefaultMutableTreeNode(canalActual.getVidPropios().get(j)));
                    }
                }
                break;
        }
        actual.setSuscripciones(canalActual);
        modeloLista.removeElementAt(this.lstAllChanels.getSelectedIndex());
        modeloArbol.reload();
        
    }//GEN-LAST:event_btnSuscribirseMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        if (this.txtNombreVid.getText().equals("")) {
            JOptionPane.showMessageDialog(this.jdAgrVideo, "Debe llenar todos los campos");
        }else{
            DefaultListModel modeloLista = (DefaultListModel) this.lstMisVideos.getModel();
            Videos v = new Videos(this.txtNombreVid.getText(), Integer.parseInt(this.spnDuracion.getValue().toString()));
            actual.getCanal().setVidPropios(v);
            modeloLista.addElement(v);
            JOptionPane.showMessageDialog(this.jdAgrVideo, "Video añadido con exito");
            this.jdAgrVideo.setVisible(false);
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.jdAgrVideo.setModal(true);
        this.jdAgrVideo.pack();
        this.jdAgrVideo.setLocationRelativeTo(this);
        this.jdAgrVideo.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    public void cargarUsers(){
        this.archivo.cargarArchivo();
        this.AllChanels = this.archivo.getListaPersonas();
        
    }
    
    public void cargarSuscripciones(){
        DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jtSuscripciones.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        int[] hijos = {-1,-1,-1,-1};
        if (actual.getSuscripciones().size() != 0) {
            for (int i = 0; i < actual.getSuscripciones().size(); i++) {
                switch(actual.getSuscripciones().get(i).getCategoria()){
                    case "VideoJuegos":
                        ((DefaultMutableTreeNode)raiz.getChildAt(0)).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i)));
                        hijos[0]++;
                        Canales canalActualV = actual.getSuscripciones().get(i);
                        if (actual.getSuscripciones().get(i).getVidPropios().size() != 0) {
                            for (int j = 0; j < actual.getSuscripciones().get(i).getVidPropios().size(); j++) {
                                ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(hijos[0])).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i).getVidPropios().get(j)));
                            }
                        }
                        break;
                    case "Musica":
                        ((DefaultMutableTreeNode)raiz.getChildAt(1)).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i)));
                        hijos[1]++;
                        Canales canalActualM = actual.getSuscripciones().get(i);
                        if (actual.getSuscripciones().get(i).getVidPropios().size() != 0) {
                            for (int j = 0; j < actual.getSuscripciones().get(i).getVidPropios().size(); j++) {
                                ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(hijos[1])).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i).getVidPropios().get(j)));
                            }
                        }
                        break;
                    case "Cocina":
                        ((DefaultMutableTreeNode)raiz.getChildAt(2)).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i)));
                        hijos[2]++;
                        Canales canalActualC = actual.getSuscripciones().get(i);
                        if (actual.getSuscripciones().get(i).getVidPropios().size() != 0) {
                            for (int j = 0; j < actual.getSuscripciones().get(i).getVidPropios().size(); j++) {
                                ((DefaultMutableTreeNode)raiz.getChildAt(2).getChildAt(hijos[2])).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i).getVidPropios().get(j)));
                            }
                        }
                        break;
                    case "Otros":
                        ((DefaultMutableTreeNode)raiz.getChildAt(3)).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i)));
                        hijos[3]++;
                        Canales canalActualO = actual.getSuscripciones().get(i);
                        if (actual.getSuscripciones().get(i).getVidPropios().size() != 0) {
                            for (int j = 0; j < actual.getSuscripciones().get(i).getVidPropios().size(); j++) {
                                ((DefaultMutableTreeNode)raiz.getChildAt(3).getChildAt(hijos[3])).add(new DefaultMutableTreeNode(actual.getSuscripciones().get(i).getVidPropios().get(j)));
                            }
                        }
                        break;
                }
            }
        }
        modeloArbol.reload();
    }
    
    public void cargarChannels(){
        DefaultListModel modeloLista = (DefaultListModel) this.lstAllChanels.getModel();
        for (int i = 0; i < AllChanels.size(); i++) {
            if (!(AllChanels.get(i).getUsuario().equals(actual.getUsuario()))) {
                if (actual.getSuscripciones().size() != 0) {
                    for (int j = 0; j < actual.getSuscripciones().size(); j++) {
                        if (!(actual.getSuscripciones().get(i).toString().equals(AllChanels.get(i).getCanal().toString()))) {
                            modeloLista.addElement(AllChanels.get(i).getCanal());
                        }
                    }
                }else{
                    modeloLista.addElement(AllChanels.get(i).getCanal());
                }
            }
        }
    }
    
    public void cargarMisVideos(){
        DefaultListModel modeloLista = (DefaultListModel) this.lstMisVideos.getModel();
        for (int i = 0; i < actual.getCanal().getVidPropios().size(); i++) {
            modeloLista.addElement(actual.getCanal().getVidPropios().get(i));
        }
        this.lstMisVideos.setModel(modeloLista);
    }
    
    public void cargarCategorias(){
        DefaultComboBoxModel modeloCMB = (DefaultComboBoxModel) this.cmbCategoria.getModel();
        for (int i = 0; i < Categorias.length; i++) {
            modeloCMB.addElement(Categorias[i]);
        }
    }
    
    public void bienvenida(){
        this.lblBienvenida.setText(actual.getUsuario());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDislike;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSuscribirse;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jdAgrVideo;
    private javax.swing.JDialog jdLogIn;
    private javax.swing.JTree jtSuscripciones;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblSubtitulos;
    private javax.swing.JLabel lblTituloVideo;
    private javax.swing.JList<String> lstAllChanels;
    private javax.swing.JList<String> lstMisVideos;
    private javax.swing.JList<String> lstPlaylist;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTextArea txtAComentarios;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtContraseñaR;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreVid;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioR;
    private javax.swing.JTextArea txtxASubtitulos;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuarios> AllChanels = new ArrayList();
    private Usuarios actual;
    private guardarUsuarios archivo  = new guardarUsuarios("./Users.raffles");;
    private final String[] Categorias = {"VideoJuegos", "Musica", "Cocina", "Otros"};
}
